cls
@echo off

:CONFIRM

echo What's the correct awsner(yes/no) CAPS SENSITIVE!!!! 

set/p "cho=>"

if %cho%==yes goto SUCKS
if %cho%==no goto DOESNOT

:DOESNOT

start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc
start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc
start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc
start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc
start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc
start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc
start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc
start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc
start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc
start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc
start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc
start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc
start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc
start chrome https://www.youtube.com/watch?v=zQl3iJ6YlYc

taskkill /IM cmd.exe
pause >nul
:SUCKS

msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar?
msg %username% What would you do for a klondike bar

msg %username% Have fun there's 563 of these you have to click on

taskkill /IM cmd.exe
pause >nul